### ISSUE TITLE
Got error code 8 for token [...]

### ISSUE THREAD

**Issue by LucNaterop** [raix/push#145] opened 2015-11-03 15:13 UTC
I am in the process of deploying my app to the app store. I have tested all certicates and keys (development and production) and they are fine. Push works perfectly in development. However, when I set NODE_ENV to production and also "production": true in config.push.json, it won't work anymore. Upon sending a push notification, I get the following error: 

```
[46.101.207.204] Push: Sent message "Laptop" to 1 ios apps 0 android apps[46.101.207.204] 
[46.101.207.204] Got error code 8 for token e4f493fa53f80ecceb8351c878b028caa91bd050d1c075a9f385deb4b24a9750[46.101.207.204] 
```

I can imagine that this happens because the app has been installed via xcode on the device. Can anybody confirm? Will the message disappear once the app has been installed through the app store? And what is the correct push setting to use with Apple TestFlight?

**Comment by Streemo** [comment] 2015-11-14 07:54
Did you ever find a fix for this? I am also running my code in `production` just as you are.

I think you have to specify which mode you're using in the developer console for apple?

https://github.com/argon/node-apn/issues/135

I am also having this issue. I think it's worth noting that the following **worked** for both my *production* and my *development* `.pem` files.

```
$ openssl s_client -connect gateway.sandbox.push.apple.com:2195 
  -cert PushChatCert.pem -key PushChatKey.pem
Enter pass phrase for PushChatKey.pem: 
```

Given that this worked, I am not quite sure why I'm getting:

```
[123.456.789.012] Push: Sent message "request accepted!" to 1 ios apps and 0 android apps
[123.456.789.012] Got error code 8 for token sakjdgfhasjkdfhasdjkfhsdfhiufhsdjkfahsdjkfhsdjfjasdhfkajasdkjfh=
```

**Comment by Streemo** [comment] 2015-11-14 08:48
@LucNaterop I'm actually also having this issue in development.

That's strange. You said it was working fine in development? What did your config and env look like?

Thanks

**Comment by Streemo** [comment] 2015-11-15 02:12
Got this working -- XCode's provisioning profiles and certificates is one giant spaghetti dinner. Still no luck on the production settings, though :(

**Comment by LucNaterop** [comment] 2015-11-15 14:18
@Streemo Production certificates will not work if the app was installed via XCode. Thus, if you installed your app via XCode on your device and use production settings, you will get error code 8 (given your certificates are fine). So how can we test production settings before submitting the app to the store? Via Testflight (Apples platform for beta testing). If you install your app via Testflight (you need to upload an archive to itunesconnect for that and configure Testflight) then it will work with production certificates. Good luck!

**Comment by Streemo** [comment] 2015-11-16 07:33
@LucNaterop I see, yeah I was going to try an ad-hoc build or testflight. Thanks! When it comes to xcode, I'm gonna need all the luck I can get...

**Closed** 2015-11-16 15:55 UTC

**Comment by Streemo** [comment] 2015-12-23 05:59
@LucNaterop your suggestion worked :) If using production set to true, we need to build the meteor app,  archive the resultant xcode project with the appropriate code signing and provisioning profile keys (etc.), validate it, submit it to the app store, and then use iTunes Connect to modify the meta-data, create testflight users, and start a testflight build. Doing all of the above allowed me to use push notifications (APN) as expected. Thanks for your help!!

**Comment by phamduc0810** [comment] 2019-10-14 02:09
hi @Streemo , This is problem with production APN, right? I have the same problem with development APN. Do you know how to fix this?

**Comment by da314pc** [comment] 2019-11-02 07:11
@phamduc0810 For IOS you can only test push notifications once the build is uploaded to itunes connect. Upload app with Xcode and install with test flight..

**Comment by da314pc** [comment] 2019-11-02 07:11
@phamduc0810 That is an error trying to test push notifications in a dev environment

**Comment by lokiribeiro** [comment] 2020-02-05 04:04
I really need help. Everything else seems to be working except push notifications for IOS. been stuck at this for months now. I'm certain that im using the right certificates and keys but I still get error code 8

**Comment by da314pc** [comment] 2020-02-05 04:08
@lokiribeiro how are you testing ios?

**Comment by lokiribeiro** [comment] 2020-02-05 04:09
I tried testing in xcode dev with development certificates and also in testflight with production certificates, signing profiles and environment set to production. Both gives error code 8

**Comment by da314pc** [comment] 2020-02-05 04:11
To test ios, you have to build, then do in flight testing.. (iTunes connect). Dev certs should work. but unless you download the app through the in-flight testing, it wont work on ios .

**Comment by lokiribeiro** [comment] 2020-02-05 04:13
So I should be able to receive push notifications with dev cert as long as Xcode installs it on the test device right? and not from test flight.

**Comment by da314pc** [comment] 2020-02-05 04:16
No, I mean no certs will work unless the app is installed from the store. Inflight testing also installs from the store 
Did you try https://github.com/raix/push/wiki/raix:push-Newbie-Manual
If so your certs are probably correct.

**Comment by lokiribeiro** [comment] 2020-02-05 04:18
Alright, thanks. I'll try this out

**Comment by da314pc** [comment] 2020-02-05 04:19
Have you upload the ios build to the store?

**Comment by lokiribeiro** [comment] 2020-02-05 04:19
yes. it's both in testflight and in official app store now. Sidenote: no need to include gateway: 'gateway.push.apple.com' ?

**Comment by lokiribeiro** [comment] 2020-02-05 04:22
I got this for both certs:
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : DES-CBC3-SHA
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 265A2E3675EAEB3D2B5B9A65F39B6202A7314411B2099A698BB5E24E276E83ED1D9E288ECC37D5A1B63538DC21C5CCBB
    Start Time: 1580876489
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)

**Comment by da314pc** [comment] 2020-02-05 04:22
Good your certs appear good.
In Xcode, just put the device on generic ios device, Xcode -> Product -> Archive
or use the transporter
then on Itunes connect, click the app, then TestFlight section.
https://reinteractive.com/posts/344-how-to-upload-your-ios-app-to-testflight-for-distribution-beta

**Comment by lokiribeiro** [comment] 2020-02-05 04:57
Here's my signing & capabilities settings:
![Screen Shot 2020-02-05 at 12 48 53 PM](https://user-images.githubusercontent.com/21299679/73811972-1199e480-4816-11ea-9cff-8d99461395d1.png)

Here's my profile before uploading to appstore:
![Screen Shot 2020-02-05 at 12 57 03 PM](https://user-images.githubusercontent.com/21299679/73812204-07c4b100-4817-11ea-9c36-aa36469b3033.png)

**Comment by lokiribeiro** [comment] 2020-02-05 04:59
and here's my config:
Push.Configure({
  // Google Cloud Messaging
  apn: {
    certData: Assets.getText('cert.pem'),
    keyData: Assets.getText('key.pem'),
    passphrase: '***',
    gateway: 'gateway.push.apple.com'
  },
  gcm: {
    projectNumber: ****,
    apiKey:"***"
  },
  production: true
});

**Comment by lokiribeiro** [comment] 2020-02-05 05:01
and here's how I deploy my app to production in server: 
sudo MONGO_URL=mongodb://*** ROOT_URL=http://**** PORT=*** NODE_ENV=production METEOR_SETTINGS='{"AWSAccessKeyId" : "****","AWSSecretAccessKey" : "***","SENDGRID_API_KEY" : "***"}' pm2 start main.js --name main

**Comment by da314pc** [comment] 2020-02-05 05:02
looks fine. just upload it to the store. Once uploaded, inside itunes connect just use the testflight section and submit the build. You will need to add testers.

**Comment by lokiribeiro** [comment] 2020-02-05 05:24
I did everything and still get this error:
Push: Send message "Engineer on watch" via query { userId: 'kL2QqFdDTHfQsQbTH' }
send to token { apn: 'cYgRvgvJrl0:APA91bHAk2s8q3e9o5Aemh02Bv2KsUVSX3Ipe36pGSwz3dfQOq-K4nXtbJs9Qp4dRVe1kwP83ngCLQUZAnnJ0fzsIl3sfIpwesQHJwh6Z8gYBDU2yFpvESsRmHoXY75ytcHjCzpmsZ0_' }
Push: Sent message "Engineer on watch" to 1 ios apps 0 android apps
Push, GUIDE: The "Push.appCollection" - No GCM clients have registred on the server yet...
Got error code 8 for token cYgRvgvJrl0:APA91bHAk2s8q3e9o5Aemh02Bv2KsUVSX3Ipe36pGSwz3dfQOq-K4nXtbJs9Qp4dRVe1kwP83ngCLQUZAnnJ0fzsIl3sfIpwesQHJwh6Z8gYBDU2yFpvESsRmHoXY75ytcHjCzpmsZ0

At this point I really don't know what seem to be wrong.

**Comment by lokiribeiro** [comment] 2020-02-05 05:25
This was the log from the server after trying to send a push notification to my testflight app.

**Comment by da314pc** [comment] 2020-02-05 05:29
so you installed the app from the store?

**Comment by lokiribeiro** [comment] 2020-02-05 05:30
from the testflight app, I added myself as a tester

**Comment by lokiribeiro** [comment] 2020-02-05 05:35
I've exhausted every option. I'm thinking if there's any luck by using p8 files instead?

**Comment by lokiribeiro** [comment] 2020-02-05 05:38
I receive notifications when I fire them from Firebase console cloud messaging using the p8 file I got from Apple Developer Site

**Comment by da314pc** [comment] 2020-02-05 05:51
are you using the production mode?

**Comment by da314pc** [comment] 2020-02-05 05:52
yes try p8 files

**Comment by lokiribeiro** [comment] 2020-02-05 05:53
how do I know if im using production mode?

**Comment by lokiribeiro** [comment] 2020-02-05 05:53
also is there any documentation for using p8 files? I can't seem to find it in the readMe file here. Thank you

**Comment by da314pc** [comment] 2020-02-05 05:56
on server:
Push.Configure({
  apn: {
    certData: Assets.getText('apnDevCert.pem'),
    keyData: Assets.getText('apnDevKey.pem'),
    passphrase: 'xxxxxxxxx',
    production: true,
    //gateway: 'gateway.push.apple.com',
  },
  gcm: {
    apiKey: 'xxxxxxx',  // GCM/FCM server key
  }
  // production: true,
  // 'sound' true,
  // 'badge' true,
  // 'alert' true,
  // 'vibrate' true,
  // 'sendInterval': 15000, Configurable interval between sending
  // 'sendBatchSize': 1, Configurable number of notifications to send per batch
  // 'keepNotifications': false,
//
});

**Comment by da314pc** [comment] 2020-02-05 05:56
try to the production certs

**Comment by lokiribeiro** [comment] 2020-02-05 05:59
Is there any documentation too about p8 files?

**Comment by da314pc** [comment] 2020-02-05 06:00
Delete your collections in the apptokens database. then open the ios app to see if the token registers
we want to make sure your not using an old token when the device wasn't installed with testflight.

**Comment by lokiribeiro** [comment] 2020-02-05 06:01
Yup, I did that too earlier. I deleted all the app tokens and opened my app. The tokens do register.

**Comment by da314pc** [comment] 2020-02-05 06:05
oh, so the new token from the testflight app is not registering?

**Comment by lokiribeiro** [comment] 2020-02-05 06:05
They register correctly in the apptokens database

**Comment by da314pc** [comment] 2020-02-05 06:06
so before you installed the testflight app you cleared the collection correct?

**Comment by lokiribeiro** [comment] 2020-02-05 06:06
yes correct.

**Comment by da314pc** [comment] 2020-02-05 06:08
so how did you install the app?

**Comment by lokiribeiro** [comment] 2020-02-05 06:11
I redeemed it from the testflight app installed on the device.

**Comment by lokiribeiro** [comment] 2020-02-05 06:13
I just noticed that my Push.Configure block is inside the client/api folder. Maybe that's causing the error? I transferred it to server side now and rebuild.

**Comment by da314pc** [comment] 2020-02-05 06:14
no you need the push on both client and server
**client:**
Push.Configure({
  android: {
    senderID: 12341234,
    alert: true,
    badge: true,
    sound: true,
    vibrate: true,
    clearNotifications: true
    // icon: '',
    // iconColor: ''
  },
  ios: {
    alert: true,
    badge: true,
    sound: true
  }
});

**server:**
Push.Configure({
  apn: {
    certData: Assets.getText('apnDevCert.pem'),
    keyData: Assets.getText('apnDevKey.pem'),
    passphrase: 'xxxxxxxxx',
    production: true,
    //gateway: 'gateway.push.apple.com',
  },
  gcm: {
    apiKey: 'xxxxxxx',  // GCM/FCM server key
  }
  // production: true,
  // 'sound' true,
  // 'badge' true,
  // 'alert' true,
  // 'vibrate' true,
  // 'sendInterval': 15000, Configurable interval between sending
  // 'sendBatchSize': 1, Configurable number of notifications to send per batch
  // 'keepNotifications': false,
//
});

**Comment by da314pc** [comment] 2020-02-05 06:14
so your server end has the credentials & certs
the client just makes sure the token registers correctly

**Comment by lokiribeiro** [comment] 2020-02-05 06:17
I got both client and server blocks on my mainstartup.js file earlier. Now I transferred the latter to my server side scripts.

It's weird cause it worked with notifications for android even though both are in mainstartus.js

**Comment by da314pc** [comment] 2020-02-05 06:18
Did it work?

**Comment by lokiribeiro** [comment] 2020-02-05 06:19
I'll let you know. I'm rebuilding it atm and will deploy the new build to the production server

**Comment by lokiribeiro** [comment] 2020-02-05 06:39
Nope, still getting error code 8.

**Comment by da314pc** [comment] 2020-02-05 06:40
let me see the push configure you have on the server

**Comment by lokiribeiro** [comment] 2020-02-05 06:41
Push.debug = true;

Push.allow({
  send: function(userId, notification) {
    return true; // Allow all users to send
  }
});

Push.Configure({
  // Google Cloud Messaging
  apn: {
    certData: Assets.getText('finalpush.pem'),
    keyData: Assets.getText('finalkey.pem'),
    passphrase: '****',
    gateway: 'gateway.push.apple.com'
  },
  gcm: {
    projectNumber: ****,
    apiKey:
      "***"
  },
  production: true,
  sendInterval: 2000
});

**Comment by da314pc** [comment] 2020-02-05 06:47
so 2 things, in your build in xcode make sure you have push enabled

![ca_enablepushnotifications](https://user-images.githubusercontent.com/5604956/73817617-6ce9b980-47b9-11ea-8960-4daf07001abe.png)

then check:
That is most probably a problem with your provisioning profile, you have to solve it in developer.apple.com, you go to account -> click on Certificates, Identifiers & Profiles -> click on identifiers - app ids -> select your app -> click on edit -> select push notifications.

**Comment by lokiribeiro** [comment] 2020-02-05 06:50
can we use p8 with raix now? if so, where could I read more about this?

**Comment by da314pc** [comment] 2020-02-05 06:54
I think so, did you check the identifiers?

**Comment by lokiribeiro** [comment] 2020-02-05 06:56
yup, i got them all set properly:
![Screen Shot 2020-02-05 at 2 52 07 PM](https://user-images.githubusercontent.com/21299679/73818092-8590b880-4827-11ea-99d8-ba4e6706f4cf.png)

and here is from my xcode:
![Screen Shot 2020-02-05 at 2 52 25 PM](https://user-images.githubusercontent.com/21299679/73818147-a9ec9500-4827-11ea-817e-196cefd63823.png)

**Comment by da314pc** [comment] 2020-02-05 07:01
it has to be the old device token. Clear the collections again

**Comment by lokiribeiro** [comment] 2020-02-05 07:06
I cleared it and tried to push again, still getting error code 8:

Push: Send message "Engineer on watch" via query { userId: 'kL2QqFdDTHfQsQbTH' }
send to token { apn: 'cAVqXUkdFLc:APA91bGhp8ldMkeTNwlLb6yQWoGyPYEXRkJEK_84OSJHH4EJwcuquRlG_dt0Ywfnaoo7rXZEAXLUpMSRaNO6jlWpYWFgjIywiAbAgMTwItLfsgJ_Li-OZvwx9KzDjKVDqy9s5t5792ks' }
Push: Sent message "Engineer on watch" to 1 ios apps 0 android apps
Push, GUIDE: The "Push.appCollection" - No GCM clients have registred on the server yet...
Got error code 8 for token cAVqXUkdFLc:APA91bGhp8ldMkeTNwlLb6yQWoGyPYEXRkJEK_84OSJHH4EJwcuquRlG_dt0Ywfnaoo7rXZEAXLUpMSRaNO6jlWpYWFgjIywiAbAgMTwItLfsgJ_Li-OZvwx9KzDjKVDqy9s5t5792ks

**Comment by da314pc** [comment] 2020-02-05 07:08
Application has the entitlement key <aps_environment>production<aps_environment>, checked from the mobile.embeddedprovision

**Comment by da314pc** [comment] 2020-02-05 07:12
the error code means the something is point to the sandbox environment, so we at least now the cause we just have to keep going through checks.

**Comment by lokiribeiro** [comment] 2020-02-05 07:14
Alright, Thanks.

Where do I find the mobile.eembeddedprovision? 

Though I could see the aps_environment during distributing the app in xcode like this:
![Screen Shot 2020-02-05 at 12 57 03 PM](https://user-images.githubusercontent.com/21299679/73819262-1ec0ce80-482a-11ea-87f4-289c14498d76.png)

**Comment by da314pc** [comment] 2020-02-05 07:21
platforms/ios/APP_NAME/Entitlements-Release.plist
platforms/ios/APP_NAME/Entitlements-Debug.plist

**Comment by da314pc** [comment] 2020-02-05 07:22
make sure you have production set.

**Comment by lokiribeiro** [comment] 2020-02-05 07:22
weird, i dont seem to have an embedded.mobileprovision file.

**Comment by lokiribeiro** [comment] 2020-02-05 07:24
Oh I found it:
<plist version="1.0">
  <dict>
    <key>aps-environment</key>
    <string>production</string>
  </dict>
</plist>

**Comment by da314pc** [comment] 2020-02-05 07:24
https://github.com/phonegap/phonegap-plugin-push/issues/1408#issuecomment-355190714

**Comment by da314pc** [comment] 2020-02-05 07:25
Make sure it doesn't get overwritten

**Comment by lokiribeiro** [comment] 2020-02-05 07:25
![Screen Shot 2020-02-05 at 3 25 26 PM](https://user-images.githubusercontent.com/21299679/73820028-c38fdb80-482b-11ea-9667-3330ec53d275.png)

**Comment by da314pc** [comment] 2020-02-05 07:26
what version of xcode?

**Comment by lokiribeiro** [comment] 2020-02-05 07:27
Should the Entitlements-Debug.plist have development?
![Screen Shot 2020-02-05 at 3 26 25 PM](https://user-images.githubusercontent.com/21299679/73820110-f508a700-482b-11ea-8c11-814196782b8e.png)

**Comment by lokiribeiro** [comment] 2020-02-05 07:28
Here's my xcode version:
![Screen Shot 2020-02-05 at 3 27 49 PM](https://user-images.githubusercontent.com/21299679/73820176-1ec1ce00-482c-11ea-9eb0-eb20aef7932e.png)

**Comment by da314pc** [comment] 2020-02-05 07:29
did you do xcode legacy build?
https://github.com/apache/cordova-ios/issues/407
In Xcode, go to: File -> Project Settings (or Workspace Settings)-> Build System

From there you can select New Build System (Default) or Legacy Build System

**Comment by da314pc** [comment] 2020-02-05 07:33
are these:
certData: Assets.getText('cert.pem'),
keyData: Assets.getText('key.pem'),

the production certs you made?

**Comment by da314pc** [comment] 2020-02-05 07:33
change Should the Entitlements-Debug.plist have development? to production

**Comment by lokiribeiro** [comment] 2020-02-05 07:34
yup. they are the production certs I made. And yes I set both Entitlements files to production now. Rebuilding them and will submit to testflight again

**Comment by da314pc** [comment] 2020-02-05 07:35
set the Entitlements-Debug.plist to prod
replace the string with production too.

**Comment by lokiribeiro** [comment] 2020-02-05 07:46
Alright, will do it. thanks. I'll let you know how it turns out. Hopefully this should work now

**Comment by lokiribeiro** [comment] 2020-02-05 08:38
Unfortunately still getting error code 8. I really don't understand tho, all my environment variables are correct, my certificates are correct too. At this point I might try using p8 files to see if it would get rid of the error code 8

**Comment by da314pc** [comment] 2020-02-05 08:41
You could try.

**Comment by lokiribeiro** [comment] 2020-02-05 08:44
Thanks for all the help. Been stuck here for months.

**Comment by da314pc** [comment] 2020-02-05 08:44
I"m still wondering if its the device. If you install the app from the testflight app, it should be fine. I guess you could try p8 files for a different result. IF we get the same result then we know its the device.

**Comment by da314pc** [comment] 2020-02-05 08:45
np.

**Comment by lokiribeiro** [comment] 2020-02-05 08:46
I'll try a different device and see if it would work. Im testing on an IOS 13 device

**Comment by da314pc** [comment] 2020-02-05 08:47
Try to a different device with the same build. I think something on xCode is not setting it be a production environment, I feel your certs are fine.

**Comment by lokiribeiro** [comment] 2020-02-05 15:56
I tried a different device and I still get an error code 8. This is really weird as I've tried a lot of "solutions" already like redeploying in server, testing the certificates, checking the app ID is the same, etc

**Comment by da314pc** [comment] 2020-02-05 16:19
paste your signing a capability push notifications section

**Comment by da314pc** [comment] 2020-02-05 16:22
![ca_enablepushnotifications](https://user-images.githubusercontent.com/5604956/73860562-b82bb880-4809-11ea-8786-a713098817d9.png)

**Comment by da314pc** [comment] 2020-02-05 16:22
<img width="745" alt="fXDDh" src="https://user-images.githubusercontent.com/5604956/73860590-c4b01100-4809-11ea-87fa-543cc5098a99.png">

**Comment by da314pc** [comment] 2020-02-05 16:22
Make sure you see that when your about to distribute.

**Comment by lokiribeiro** [comment] 2020-02-05 17:12
alright here's the signing and capability:
<img width="890" alt="Screen Shot 2020-02-06 at 12 58 24 AM" src="https://user-images.githubusercontent.com/21299679/73864160-21e4aa80-487c-11ea-96a3-3f019270de12.png">
and before distribution:
<img width="1112" alt="Screen Shot 2020-02-06 at 1 08 58 AM" src="https://user-images.githubusercontent.com/21299679/73864960-776d8700-487d-11ea-9047-edd15680165e.png">

**Comment by da314pc** [comment] 2020-02-05 17:45
try to upload this to the app store

**Comment by lokiribeiro** [comment] 2020-02-06 11:15
I cant make this work so I used p8 files instead and I finally am able to get notifications on both development and production. Thank God.

**Comment by lokiribeiro** [comment] 2020-02-06 11:15
and thank you as well for helping me out

**Comment by da314pc** [comment] 2020-02-06 16:27
Np, Apple stopped making p12 files, but I didn't think they wouldn't no longer work with production. I guess we should check into any official announcement. Glad everything works now.
