### ISSUE TITLE
RangeError: Maximum call stack size exceeded on first connection of cordova client

### ISSUE THREAD

**Issue by bastiRe** [raix/push#51] opened 2015-03-23 04:08 UTC
I have a hybrid meteor app with Android and iOS clients. The first time after the installation of the app one of these clients connects my server it throws an error and restarts. This is the log that I get:
    
    W20150323-14:03:25.841(10)? (STDERR)
    W20150323-14:03:25.842(10)? (STDERR) /Users/BastiR/.meteor/packages/meteor-tool/.1.0.43.1v54ord++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
    W20150323-14:03:25.842(10)? (STDERR) 						throw(ex);
    W20150323-14:03:25.842(10)? (STDERR) 						      ^
    W20150323-14:03:25.843(10)? (STDERR) RangeError: Maximum call stack size exceeded

I only have this error with the push package installed and it only happens with Cordova clients not a web client. After the server has restarted the responsible Cordova client connects fine. It's just the first connection that provokes the restart. It seems to me that it has something to do with the push setup for new clients. Push itself works fine afterwards for Android and iPhone. I only have development certificates for push and push is in development mode. Any ideas what causes this behaviour?

**Comment by raix** [comment] 2015-03-23 07:17
@bastiRe what version of raix:push are you using?
So this only happens when the client connects the first time / doesn't have a token?

Would be nice to figure this one out

**Comment by bastiRe** [comment] 2015-03-23 07:30
I’m using 2.6.4. 
It only happens when the client connects the first time. The interesting difference is that it happens on Android again after uninstalling the app and installing it again whereas it only happens the first time the app is installed on an iOS device. Reinstalling the app on iOS doesnt’t trigger the behaviour.

**Comment by dennisharrison** [comment] 2015-03-25 16:21
I haven't seen this on iOS or Android yet.  Will try uninstalling and reinstalling on Android in an hour or so.

**Comment by raix** [comment] 2015-03-25 16:23
@bastiRe what setup are you on/os etc.?

**Comment by Weijtmans** [comment] 2015-03-25 16:45
I'm having the same issue when a user connects to the server for the server for the first time and inserts its push token. The crash only seems to only occur on iOS. I'm using the latest meteor and raix:push.

**Comment by dennisharrison** [comment] 2015-03-25 18:06
@bastiRe & @Weijtmans
Can you give details about the environment that your server is running in?

**Comment by dennisharrison** [comment] 2015-03-25 18:51
Can't reproduce on my versions.  

I'm on OS X 10.10.2 using Meteor 1.0.4.2 and Push 2.6.2

I'll try upgrading Push and see if that does anything.

**Comment by raix** [comment] 2015-03-25 20:29
I'm marking this as a bug - I've seen this behaviour before I think, but unable to replicate.

-

STATS:

OS
* [ ] ~~mac os~~
* [ ] linux
* [ ] ~~windows~~

Platform related
* [x] iOS
* [x] android

When
* [x] New users inserts token first time

what throws errors
* [x] Server
* [ ] ~~Client~~

Versions
* [x] raix:push@2.6.4

**Comment by Weijtmans** [comment] 2015-03-25 21:12
@dennisharrison No problem. I'm running Digital Ocean droplet (1GB/1CPU) with the Ubuntu 14.04 X64 image. Running Meteor (1.0.4.2) deployed with Meteor Up (with Node 0.10.36). I'm using Raix:Push (2.6.4) in production in combination with the following packages:
aldeed:collection2: 2.3.2
cordova:org.apache.cordova.dialogs: 0.3.0
cordova:org.apache.cordova.network-information: 0.2.15
d0minikk:materialize-meteor: 1.95.1
dburles:google-maps: 1.0.8
fastclick: 1.0.3
ground:db: 0.3.6 
harrison:papa-parse: 1.0.10
iron:router: 1.0.7 
matteodem:easy-search: 1.4.13 
meteor-platform: 1.2.2
meteorhacks:cluster: 1.6.1
meteorhacks:kadira: 2.20.1 
meteorhacks:subs-manager: 1.3.0
mobile-status-bar: 1.0.3
natestrauser:connection-banner: 0.4.3
okgrow:iron-router-autoscroll: 0.0.7  
reywood:iron-router-ga: 0.5.3  
standard-app-packages: 1.0.5
steeve:jquery-qrcode: 0.2.2
underscore: 1.0.3
zimme:iron-router-active: 1.0.1

If you need any more info, feel free to ask. I can provide you with the logs and access to our server if needed.

**Comment by bastiRe** [comment] 2015-03-25 23:52
My server is hosted via Modulus with 512mb/1 cpu. However, I can see the same error on my local development Macbook with OSX 10.10. However, the restart of the local server is so fast that it's not noticeable in the app.
I'm currently using Meteor 1.0.4 and this is a list of my packages:
accounts-password                                      1.1.0
aldeed:autoform                                           4.2.2*
aldeed:collection2                                        2.3.2 
aldeed:simple-schema                                 1.3.1
anti:fake                                                       0.4.1  
cordova:com.cowbell.cordova.geofence                  
cordova:com.phonegap.plugins.facebookconnect           
cordova:de.appplant.cordova.plugin.local-notification 
fourseven:scss                                         2.0.1_4*
iron:router                                                   1.0.7
mdg:geolocation                                         1.0.2
meteor-platform                                          1.2.2
meteoric:autoform-ionic                              0.1.5 
meteoric:ionic                                             0.1.17+
meteoric:ionic-sass                                     0.1.9  
meteoric:ionicons-sass                               0.1.6  
momentjs:moment                                      2.9.0  
particle4dev:cordova-fb                              1.1.3 
raix:push                                                     2.6.4 
sacha:spin                                                  2.0.4
service-configuration                                  1.0.4 
useraccounts:ionic                                     1.8.1

**Comment by Weijtmans** [comment] 2015-03-26 08:12
I pulled the following from the logs and Kadira (on or right before the server crash).
Logs:
Push: updated { token: { apn: 'APN OF CLIENT' },
  appName: 'main',
  userId: null,
  createdAt: Wed Mar 25 2015 11:14:06 GMT-0400 (EDT),
  updatedAt: Wed Mar 25 2015 11:14:06 GMT-0400 (EDT),
  _id: [ [Circular] ] }
undefined

From Kadira:
Maximum call stack size exceeded
Cannot read property 'canonical_ids' of null
TypeError: Cannot read property 'canonical_ids' of null
    at packages/raix:push/lib/server/push.api.js:243:1
    at lambda (/opt/erasmus-master/app/programs/server/npm/raix_push/node_modules/node-gcm/lib/sender.js:116:20)
    at IncomingMessage.<anonymous> (/opt/erasmus-master/app/programs/server/npm/raix_push/node_modules/node-gcm/lib/sender.js:66:21)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)

**Comment by raix** [comment] 2015-03-26 09:01
@Weijtmans I'll have a look at it

**Comment by dennisharrison** [comment] 2015-03-26 14:51
@Weijtmans I'm also running this on a digital ocean 1gb droplet w/ 14.04 lts and don't see it - shoot.

**Comment by Weijtmans** [comment] 2015-03-26 16:25
@dennisharrison I can give you temporary access to the droplet if that helps. Please feel free to contact me at elgar@brightbind.com.

**Comment by raix** [comment] 2015-03-26 17:44
Could you guys test out Published raix:push@2.6.5

It's minor changes made - I'm wondering why android send returns no error but result == null on some systems - We'll have to investigate

**Comment by bastiRe** [comment] 2015-03-27 01:44
As far as I can tell the error is gone. Good job.

**Comment by Weijtmans** [comment] 2015-03-27 08:45
I tested locally (on OSX and on Ubunutu 14.04 with both iOS and Android clients). The problem seems to be fixed. Great work.  Thank you!

**Comment by raix** [comment] 2015-03-27 09:12
Cool,
Thanks guys!

I'm keeping this open just a bit more - I'm still thinking it's odd that the result is null on some platforms. So we should prop. want to investigate further.

**Comment by adeelraza** [comment] 2015-03-28 05:29
I'm having the same issue. Upgrading to 2.6.5 starts giving a different error in Modulus logs:

Exception in setInterval callback: Error: Push: Error while parsing query string

**Comment by raix** [comment] 2015-03-28 05:53
@adeelraza It's another issue tracked in #52

**Closed** 2015-03-28 05:59 UTC
Labels: bug
